'use strict';
const $ = selector => document.querySelector(selector);
const icon = name => `<svg aria-hidden="true"><use href="#${name}"/></svg>`;
let documentText = '', documentName = '', activeCategory = '전체', toastTimer;
const guides = [
  {category:'시작하기',title:'첫 도구는 작고 명확하게',description:'한 번에 모든 업무를 바꾸기보다, 자주 반복하는 한 가지 일부터 시작해보세요.',sections:[['반복되는 한 장면을 고르세요','매일 같은 값을 옮겨 적거나, 같은 질문에 답하는 순간을 찾아보세요. 누가, 언제, 무엇 때문에 번거로운지 한 문장으로 적습니다.'],['첫 버전의 완료 기준을 정하세요','“장비 예약을 편하게”보다 “팀원이 날짜와 장비를 선택해 예약하고, 예약 목록을 확인한다”처럼 실제 행동으로 정의하세요.'],['다음 버전으로 미룰 것도 적으세요','알림, 통계, 다른 시스템 연동은 반드시 첫 버전에 필요한지 확인합니다. 먼저 한 가지 흐름이 끝까지 동작하도록 만들어보세요.']]},
  {category:'요청 잘하기',title:'AI에게 업무 맥락을 먼저 알려주세요',description:'누가 쓰는지, 지금 어떤 문제가 있는지 알려주면 요청이 훨씬 구체적이 됩니다.',sections:[['사용자 · 문제 · 원하는 결과','개발 기술부터 정하기보다 현재 업무를 설명하세요. 실제 쓰는 용어와 입력 예시를 함께 적으면 서로 다른 해석을 줄일 수 있습니다.'],['이렇게 요청해보세요','팀원 20명이 사용하는 장비 예약 도구를 만들고 싶습니다. 현재 메신저로 예약을 받아 중복 예약이 생깁니다. 날짜별 예약을 확인하고, 비어 있는 시간에 예약하는 흐름을 먼저 구성해주세요.'],['모르는 부분은 질문해달라고 하세요','“정해지지 않은 내용은 임의로 확정하지 말고 질문으로 정리해줘”를 덧붙이세요. 사용자 권한과 승인 절차처럼 업무 정책이 필요한 부분을 함께 확인할 수 있습니다.']]},
  {category:'요청 잘하기',title:'완성된 초기 프롬프트로 개발 시작하기',description:'정리한 목적, 사용자, 주요 기능을 바탕으로 AI와 같은 그림을 보며 시작하세요.',sections:[['초안부터 검토하세요','입력한 업무가 정확하게 반영되었는지 확인합니다. ‘확인 필요’ 항목은 업무 담당자와 논의하고, 실제로 필요하지 않은 기능은 제외하세요.'],['화면 한 개부터 요청하세요','개발 정의서를 전달하고 “사용자가 가장 자주 하는 작업의 화면부터 목업으로 만들어줘”라고 요청해보세요. 화면에서 빠진 입력과 동작을 찾기 쉬워집니다.'],['작업 단위를 작게 나누세요','목록 확인 → 신규 입력 → 수정과 삭제 순으로 한 단계씩 요청하고 확인하세요. 한 번에 많은 기능을 바꾸면 문제가 생긴 지점을 찾기 어렵습니다.']]},
  {category:'검토와 개선',title:'정상 동작 다음에는 예외 상황 확인',description:'빈 입력, 중복 등록, 저장 실패까지 확인하면 실제 업무에서 더 편하게 쓸 수 있어요.',sections:[['같은 순서로 직접 사용해보세요','목록을 열고, 새 내용을 입력하고, 저장한 뒤 다시 확인합니다. 기존 업무의 순서와 맞는지 실제 사용자 관점에서 살펴보세요.'],['잘못된 입력도 넣어보세요','필수 내용을 비웠을 때, 날짜 순서가 잘못됐을 때, 같은 항목을 두 번 등록했을 때를 확인합니다. 해결 방법이 보이는 안내 문구가 있는지도 확인하세요.'],['완료 기준을 문장으로 남기세요','“중복 예약은 저장되지 않고 다른 시간을 선택하라는 안내가 보인다”처럼 기대 결과를 적어두면 수정 후에도 같은 기준으로 확인할 수 있습니다.']]},
  {category:'시작하기',title:'실제 데이터 전에 예시 데이터로',description:'업무의 형태를 닮은 가상 데이터로 필요한 입력과 화면 구성을 먼저 확인하세요.',sections:[['값보다 구조를 먼저 살펴보세요','실제 명단 대신 ‘사용자 A’, 실제 장비 번호 대신 ‘장비 01’을 사용하세요. 필요한 항목, 항목 사이의 관계, 업무 흐름을 먼저 확인할 수 있습니다.'],['현실적인 경우를 섞어보세요','긴 제목, 항목이 없는 목록, 여러 날짜에 걸친 예약처럼 실제 업무에서 만날 수 있는 예시를 포함하세요.'],['실제 사용 전 확인할 내용을 남기세요','데이터 출처, 접근 가능한 사용자, 저장 위치와 운영 담당자를 확인 사항에 적어두고 사내 운영 기준에 맞게 정리하세요.']]},
  {category:'검토와 개선',title:'수정 요청은 한 번에 한 가지씩',description:'기대했던 동작과 실제 동작을 나눠 적으면 개선할 부분을 더 정확하게 전달할 수 있어요.',sections:[['재현 순서를 적으세요','어떤 화면에서 무엇을 눌렀는지 순서대로 남깁니다. 오류 메시지가 있다면 함께 기록하세요.'],['기대와 실제를 나눠 적으세요','기대: 예약 취소 후 목록에서 해당 항목이 사라진다.\n실제: 취소 완료 메시지가 보이지만 항목이 그대로 남아 있다.'],['수정한 뒤 같은 흐름을 확인하세요','같은 순서로 다시 사용해보고, 주변의 정상 기능도 함께 확인합니다. 수정 전 상태를 되돌릴 수 있도록 변경 이력도 남겨두세요.']]}
];
function openGuide(index){const guide=guides[index];$('#guide-dialog-category').textContent=guide.category;$('#guide-dialog-title').textContent=guide.title;const body=$('#guide-dialog-body');body.replaceChildren();guide.sections.forEach(([title,text])=>{const heading=document.createElement('h3');heading.textContent=title;const content=document.createElement('p');content.textContent=text;body.append(heading,content);});$('#guide-dialog').showModal();}
function renderGuides(){const query=$('#guide-search').value.trim().toLocaleLowerCase();const grid=$('#guide-grid');grid.replaceChildren();guides.forEach((guide,index)=>{if(activeCategory!=='전체'&&guide.category!==activeCategory)return;if(query&&![guide.title,guide.description,guide.category,...guide.sections.flat()].join(' ').toLocaleLowerCase().includes(query))return;const card=document.createElement('button');card.className='guide-card';card.innerHTML=`<span class="guide-card-top"><span class="category-label">${guide.category}</span><span>GUIDE 0${index+1}</span></span><h3>${guide.title}</h3><p>${guide.description}</p><span class="guide-card-bottom"><span>DX추진랩 · 예시 가이드</span>${icon('arrow')}</span>`;card.addEventListener('click',()=>openGuide(index));grid.append(card);});$('#no-guides').hidden=grid.children.length>0;}
['전체','시작하기','요청 잘하기','검토와 개선'].forEach(category=>{const button=document.createElement('button');button.className='category-button';button.textContent=category;button.setAttribute('aria-pressed',String(category===activeCategory));button.addEventListener('click',()=>{activeCategory=category;document.querySelectorAll('.category-button').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));renderGuides();});$('#guide-categories').append(button);});
$('#guide-search').addEventListener('input',renderGuides);$('#close-guide').addEventListener('click',()=>$('#guide-dialog').close());renderGuides();
