-- Service schema; account references use platform. Generated from validated legacy schema.
CREATE COLLATION IF NOT EXISTS nocase (provider=icu, locale='und-u-ks-level2', deterministic=false);
CREATE TABLE IF NOT EXISTS "workspaces" (
      token_hash TEXT PRIMARY KEY, state TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 0,
      updated_at TEXT NOT NULL, expires_at INTEGER NOT NULL
    , background_agent TEXT, user_id TEXT);
CREATE TABLE IF NOT EXISTS "prompts" (
    prompt_id TEXT PRIMARY KEY, user_id TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '', stage INTEGER NOT NULL DEFAULT 1, task_type TEXT, question_index INTEGER NOT NULL DEFAULT 0,
    agent_meta TEXT, survey_signature TEXT NOT NULL DEFAULT '', survey_done INTEGER NOT NULL DEFAULT 0,
    survey_done_basis TEXT NOT NULL DEFAULT '', revision INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT, shared_at TEXT, sharing_enabled INTEGER NOT NULL DEFAULT 0, source_prompt_id TEXT, library_hidden_at TEXT);
CREATE TABLE IF NOT EXISTS "chat_messages" (
    prompt_id TEXT NOT NULL, message_id TEXT NOT NULL,
    seq INTEGER NOT NULL, role TEXT NOT NULL CHECK(role IN ('user','assistant')), content TEXT NOT NULL,
    llm_request_id TEXT, created_at TEXT NOT NULL, PRIMARY KEY (prompt_id, message_id));
CREATE TABLE IF NOT EXISTS "background_items" (
    prompt_id TEXT NOT NULL, category TEXT NOT NULL,
    status TEXT NOT NULL, summary TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', evidence TEXT NOT NULL DEFAULT '[]',
    updated_at TEXT NOT NULL, PRIMARY KEY (prompt_id, category));
CREATE TABLE IF NOT EXISTS "task_definitions" (
    prompt_id TEXT NOT NULL,
    kind TEXT NOT NULL CHECK(kind IN ('draft','confirmed')),
    name TEXT NOT NULL, background TEXT NOT NULL, users TEXT NOT NULL, scope TEXT NOT NULL,
    signature TEXT, updated_at TEXT NOT NULL, PRIMARY KEY (prompt_id, kind));
CREATE TABLE IF NOT EXISTS "survey_topics" (
    prompt_id TEXT NOT NULL, topic_id TEXT NOT NULL,
    seq INTEGER NOT NULL, label TEXT NOT NULL, description TEXT NOT NULL, origin INTEGER NOT NULL DEFAULT 0,
    empty_text TEXT, status TEXT, reason TEXT NOT NULL DEFAULT '', PRIMARY KEY (prompt_id, topic_id));
CREATE TABLE IF NOT EXISTS "survey_questions" (
    prompt_id TEXT NOT NULL, question_id TEXT NOT NULL,
    position INTEGER NOT NULL, topic_id TEXT NOT NULL, label TEXT NOT NULL, title TEXT NOT NULL, help TEXT NOT NULL,
    multi INTEGER NOT NULL, cards TEXT NOT NULL, basis TEXT NOT NULL, topic_status TEXT,
    llm_request_id TEXT, created_at TEXT NOT NULL, decision TEXT, PRIMARY KEY (prompt_id, question_id));
CREATE TABLE IF NOT EXISTS "survey_answers" (
    prompt_id TEXT NOT NULL, question_id TEXT NOT NULL, selected TEXT NOT NULL, custom TEXT NOT NULL,
    updated_at TEXT NOT NULL, PRIMARY KEY (prompt_id, question_id));
CREATE TABLE IF NOT EXISTS "prompt_documents" (
    prompt_id TEXT PRIMARY KEY, content TEXT NOT NULL,
    source TEXT NOT NULL CHECK(source IN ('generated','edited')), updated_at TEXT NOT NULL, llm_request_id TEXT, spec TEXT);
CREATE TABLE IF NOT EXISTS "llm_requests" (
    request_id TEXT PRIMARY KEY, user_id TEXT,
    prompt_id TEXT,
    step TEXT NOT NULL, provider TEXT NOT NULL, model TEXT NOT NULL, reasoning_effort TEXT,
    input_tokens INTEGER, output_tokens INTEGER, total_tokens INTEGER, cached_input_tokens INTEGER, reasoning_tokens INTEGER,
    attempt INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('success','failed','cancelled')), error_type TEXT,
    started_at TEXT NOT NULL, completed_at TEXT, duration_ms INTEGER);
CREATE TABLE IF NOT EXISTS "prompt_recommendations" (
    prompt_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    created_at TEXT NOT NULL, PRIMARY KEY (prompt_id, user_id));
CREATE TABLE IF NOT EXISTS "prompt_edit_turns" (
    turn_id TEXT NOT NULL, prompt_id TEXT NOT NULL,
    user_id TEXT NOT NULL, base_revision INTEGER NOT NULL,
    user_message TEXT NOT NULL, assistant_message TEXT NOT NULL DEFAULT '', before_text TEXT NOT NULL, after_text TEXT,
    status TEXT NOT NULL CHECK(status IN ('generating','answered','proposed','accepted','rejected','failed','stale')),
    decision_message TEXT NOT NULL DEFAULT '', llm_request_id TEXT,
    created_at TEXT NOT NULL, resolved_at TEXT, PRIMARY KEY (prompt_id,turn_id),entry_seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);
CREATE TABLE IF NOT EXISTS "personal_prompts" (
                prompt_id TEXT PRIMARY KEY,
                user_id TEXT NOT NULL,
                source_prompt_id TEXT,
                UNIQUE(user_id, source_prompt_id));
CREATE UNIQUE INDEX workspaces_user ON workspaces(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX prompts_user ON prompts(user_id, updated_at);
CREATE INDEX llm_requests_started ON llm_requests(started_at);
CREATE INDEX llm_requests_user ON llm_requests(user_id, started_at);
CREATE INDEX prompts_shared ON prompts(shared_at) WHERE shared_at IS NOT NULL;
CREATE INDEX prompt_edit_pending ON prompt_edit_turns(prompt_id,status);
ALTER TABLE "prompts" ADD CONSTRAINT "prompts_fk_0" FOREIGN KEY ("source_prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "prompts" ADD CONSTRAINT "prompts_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_fk_0" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "background_items" ADD CONSTRAINT "background_items_fk_0" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "task_definitions" ADD CONSTRAINT "task_definitions_fk_0" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "survey_topics" ADD CONSTRAINT "survey_topics_fk_0" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "survey_questions" ADD CONSTRAINT "survey_questions_fk_0" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "survey_answers" ADD CONSTRAINT "survey_answers_fk_0" FOREIGN KEY ("prompt_id","question_id") REFERENCES "wiacoding"."survey_questions" ("prompt_id","question_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "prompt_documents" ADD CONSTRAINT "prompt_documents_fk_0" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "llm_requests" ADD CONSTRAINT "llm_requests_fk_0" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "llm_requests" ADD CONSTRAINT "llm_requests_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "prompt_recommendations" ADD CONSTRAINT "prompt_recommendations_fk_0" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "prompt_recommendations" ADD CONSTRAINT "prompt_recommendations_fk_1" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "prompt_edit_turns" ADD CONSTRAINT "prompt_edit_turns_fk_0" FOREIGN KEY ("llm_request_id") REFERENCES "wiacoding"."llm_requests" ("request_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "prompt_edit_turns" ADD CONSTRAINT "prompt_edit_turns_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "prompt_edit_turns" ADD CONSTRAINT "prompt_edit_turns_fk_2" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "personal_prompts" ADD CONSTRAINT "personal_prompts_fk_0" FOREIGN KEY ("source_prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE SET NULL ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "personal_prompts" ADD CONSTRAINT "personal_prompts_fk_1" FOREIGN KEY ("user_id") REFERENCES "platform"."users" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "personal_prompts" ADD CONSTRAINT "personal_prompts_fk_2" FOREIGN KEY ("prompt_id") REFERENCES "wiacoding"."prompts" ("prompt_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
