import { useEffect, useState } from 'react';
import { Eye, Loader2, RefreshCw, Search, Trash2 } from 'lucide-react';
import { request } from './api.js';
import { Detail as PromptDetail } from './SharedPrompts.jsx';
import './admin-dashboard.css';

const number = value => Number(value || 0).toLocaleString('ko-KR');
const dateTime = value => value ? new Date(value).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' }) : '—';
const statuses = { success: '성공', failed: '실패', cancelled: '취소' };
const steps = { background: '과제 정의', background_agent: '과제 정의', background_interview: '과제 정의', survey_question: '설문 질문', prompt_generation: '프롬프트 생성', prompt_edit: 'Agent 수정' };
function initialRange() { const end = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); const start = new Date(end+'T00:00:00Z'); start.setUTCDate(start.getUTCDate()-29); return { start: start.toISOString().slice(0,10), end }; }
function Panel({ title, children }) { return <section className="panel admin-panel"><h2>{title}</h2>{children}</section>; }
function Stat({ label, value, note }) { return <div className="panel admin-stat"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }
function Table({ headers, children, empty }) { return <div className="admin-table-scroll"><table><thead><tr>{headers.map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{children}</tbody></table>{empty && <p className="admin-empty">표시할 기록이 없습니다.</p>}</div>; }
function Pages({ offset, size, total, onChange }) { return <nav className="admin-pagination" aria-label="관리 목록 페이지"><span>{number(total)}건 · {total ? offset+1 : 0}–{Math.min(offset+size,total)}</span><button className="button" disabled={!offset} onClick={() => onChange(Math.max(0,offset-size))}>이전</button><button className="button" disabled={offset+size>=total} onClick={() => onChange(offset+size)}>다음</button></nav>; }
function Operations({ data }) { const s=data.snapshot,u=data.usage; return <>
  <h2 className="admin-subtitle">현재 현황</h2><div className="admin-stats"><Stat label="활성 일반 계정" value={number(s.users)} /><Stat label="진행 중 원본" value={number(s.in_progress)} /><Stat label="확정 원본" value={number(s.confirmed)} /><Stat label="공유 중" value={number(s.shared)} /><Stat label="개인 사본" value={number(s.personal)} /></div>
  <h2 className="admin-subtitle">선택 기간의 LLM 호출</h2><div className="admin-stats"><Stat label="전체 호출" value={number(u.calls)} /><Stat label="실패" value={number(u.failed)} /><Stat label="취소" value={number(u.cancelled)} /><Stat label="평균 응답 시간" value={u.average_duration_ms==null?'—':(u.average_duration_ms/1000).toFixed(1)+'초'} /></div>
  <Panel title="사용자별 이용 현황 · 최대 100명"><Table headers={['사용자 / 사번','팀','생성 원본·사본','LLM 호출','최근 로그인']} empty={!data.activity.length}>{data.activity.map(r=><tr key={r.employee_id}><td><strong>{r.full_name}</strong><small>{r.employee_id}</small></td><td>{r.team_name}</td><td>{number(r.prompts)}</td><td>{number(r.calls)}</td><td>{dateTime(r.last_login_at)}</td></tr>)}</Table></Panel>
  <Panel title="최근 실패·취소 기록 · 최대 50건"><Table headers={['시각','사용자','단계 / 모델','상태','오류 유형']} empty={!data.errors.length}>{data.errors.map(r=><tr key={r.request_id}><td>{dateTime(r.started_at)}</td><td>{r.full_name||'삭제된 계정'}</td><td>{steps[r.step]||r.step}<small>{r.model}</small></td><td>{statuses[r.status]}</td><td>{r.error_type||'—'}</td></tr>)}</Table></Panel>
</>; }
function Tokens({ data, offset, setOffset }) { const s=data.summary; const maximum=Math.max(1,...data.groups.daily.map(r=>r.total_tokens)); return <>
  <div className="admin-stats"><Stat label="LLM 호출" value={number(s.calls)} note="재시도 호출 포함" /><Stat label="전체 토큰" value={number(s.total_tokens)} note={`입력 ${number(s.input_tokens)} · 출력 ${number(s.output_tokens)}`} /><Stat label="캐시 입력 토큰" value={number(s.cached_tokens)} note="입력 토큰에 포함" /><Stat label="토큰 미기록 호출" value={number(s.unknown_usage)} note="미기록 호출은 토큰 합계에서 제외" /></div>
  <Panel title="일별 토큰 사용량"><div className="admin-chart">{data.groups.daily.length ? data.groups.daily.map(r=><div className="admin-chart-row" key={r.day}><span>{r.day}</span><div><i style={{width:`${r.total_tokens/maximum*100}%`}} /></div><strong>{number(r.total_tokens)}</strong></div>) : <p className="admin-empty">표시할 기록이 없습니다.</p>}</div></Panel>
  <div className="admin-columns">{[['models','모델별 사용량'],['users','사용자별 사용량']].map(([key,label])=><Panel key={key} title={label}><Table headers={['구분','호출','입력','출력','전체']} empty={!data.groups[key].length}>{data.groups[key].map(r=><tr key={key==='models'?r.provider+':'+r.model:r.user_id||'deleted'}><td>{r.model||r.full_name}{r.provider&&<small>{r.provider}</small>}</td><td>{number(r.calls)}</td><td>{number(r.input_tokens)}</td><td>{number(r.output_tokens)}</td><td>{number(r.total_tokens)}</td></tr>)}</Table></Panel>)}</div>
  <Panel title="LLM 호출 기록"><Table headers={['시각','사용자','단계 / 모델','입력 / 출력','상태','소요 시간']} empty={!data.items.length}>{data.items.map(r=><tr key={r.request_id}><td title={r.request_id}>{dateTime(r.started_at)}</td><td>{r.full_name||'삭제된 계정'}</td><td>{steps[r.step]||r.step}<small>{r.provider} / {r.model}</small></td><td>{r.input_tokens==null?'—':number(r.input_tokens)} / {r.output_tokens==null?'—':number(r.output_tokens)}</td><td>{statuses[r.status]}{r.error_type&&<small>{r.error_type}</small>}</td><td>{r.duration_ms==null?'—':(r.duration_ms/1000).toFixed(1)+'초'}</td></tr>)}</Table><Pages offset={offset} size={50} total={s.calls} onChange={setOffset} /></Panel>
</>; }
function Prompts({ data, offset, setOffset, reload }) {
  const [detail,setDetail]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function change(item,remove=false){if(remove&&!window.confirm(`'${item.title||'새 프롬프트'}'를 전체 삭제할까요?\n문서와 관련 이력, 작성자 자신의 개인 사본까지 삭제되며 되돌릴 수 없습니다.`))return;setBusy(true);setError('');try{await request(`/admin/prompts/${item.prompt_id}${remove?'':'/sharing'}`,{method:remove?'DELETE':'PUT',...(remove?{}:{body:{enabled:!item.shared_at}})});reload();}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Panel title="전체 프롬프트">{error&&<p role="alert" className="auth-error">{error}</p>}<Table headers={['제목','작성자 / 팀','구분','상태','최근 수정','공유','관리']} empty={!data.items.length}>{data.items.map(r=><tr key={r.prompt_id}><td className="admin-prompt-title"><button className="text-button" onClick={()=>setDetail(r)}>{r.title||'새 프롬프트'}</button></td><td>{r.full_name}<small>{r.team_name} · {r.employee_id}</small></td><td>{r.personal?'개인 사본':'원본'}{r.library_hidden_at&&<small>개인 목록에서 제거됨</small>}</td><td>{r.completed_at?'확정':r.stage===3?'확정 대기':r.stage===2?'설문 진행':'과제 정의'}</td><td>{dateTime(r.updated_at)}</td><td>{r.personal?'개인 보관':<button className="button" disabled={busy||!r.completed_at} aria-label={`${r.title} 공유`} aria-pressed={Boolean(r.shared_at)} onClick={()=>change(r)}>{r.shared_at?'활성화':'비활성화'}</button>}</td><td><div className="account-row-actions"><button className="icon-button" aria-label={`${r.title} 상세`} onClick={()=>setDetail(r)}><Eye size={17}/></button><button className="icon-button delete-account" aria-label={`${r.title} 전체 삭제`} disabled={busy} onClick={()=>change(r,true)}><Trash2 size={17}/></button></div></td></tr>)}</Table><Pages offset={offset} size={20} total={data.total} onChange={setOffset}/>{detail&&<PromptDetail admin promptId={detail.prompt_id} onClose={()=>setDetail(null)}/>}</Panel>;
}
const titles={operations:['운영 관리','사용 현황과 LLM 처리 상태를 확인하세요.'],prompts:['프롬프트 관리','원본과 개인 사본을 조회하고 공유 상태를 관리하세요.'],tokens:['토큰 관리','모델·사용자별 토큰 사용량과 호출 기록을 확인하세요.']};
export default function AdminDashboard({ mode }) {
  const [range,setRange]=useState(initialRange);const [filters,setFilters]=useState({q:'',kind:'all',user_id:'',model:'',status:''});const [offset,setOffset]=useState(0);const [version,setVersion]=useState(0);const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);setError('');const timer=setTimeout(()=>{request(`/admin/${mode}?`+new URLSearchParams({...range,...filters,offset})).then(value=>{if(active){const total=mode==='prompts'?value.total:mode==='tokens'?value.summary.calls:0;const size=mode==='prompts'?20:50;if(offset&&offset>=total){setOffset(Math.max(0,Math.ceil(total/size)-1)*size);return}setData(value)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});},filters.q?200:0);return()=>{active=false;clearTimeout(timer)};},[mode,range,filters,offset,version]);
  const update=(key,value)=>{setFilters(f=>({...f,[key]:value}));setOffset(0)};
  return <main className="admin-page"><header className="page-heading"><div><span className="eyebrow">ADMIN WORKSPACE</span><h1>{titles[mode][0]}</h1><p>{titles[mode][1]}</p></div><button className="button" disabled={loading} onClick={()=>setVersion(v=>v+1)}><RefreshCw size={15}/>새로고침</button></header>
    <div className="panel admin-filters">{mode==='prompts'?<><label className="admin-search"><span><Search size={14}/>프롬프트 검색</span><input value={filters.q} onChange={e=>update('q',e.target.value)} placeholder="제목, 이름, 사번, 팀"/></label><label>구분<select value={filters.kind} onChange={e=>update('kind',e.target.value)}>{[['all','전체'],['active','진행 중 원본'],['confirmed','확정 원본'],['shared','공유 중'],['personal','개인 사본']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></>:<><label>시작일<input type="date" value={range.start} onChange={e=>{setRange({...range,start:e.target.value});setOffset(0)}}/></label><label>종료일<input type="date" value={range.end} onChange={e=>{setRange({...range,end:e.target.value});setOffset(0)}}/></label><button className="button" onClick={()=>{setRange(initialRange());setOffset(0)}}>최근 30일</button></>}
    {mode==='tokens'&&<><label>사용자<select value={filters.user_id} onChange={e=>update('user_id',e.target.value)}><option value="">전체 사용자</option>{data?.options.users.map(u=><option key={u.user_id} value={u.user_id}>{u.full_name} ({u.employee_id})</option>)}</select></label><label>모델<select value={filters.model} onChange={e=>update('model',e.target.value)}><option value="">전체 모델</option>{data?.options.models.map(m=><option key={m}>{m}</option>)}</select></label><label>상태<select value={filters.status} onChange={e=>update('status',e.target.value)}><option value="">전체 상태</option>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></>}
    </div>
    {error?<p className="auth-error" role="alert">{error}</p>:loading?<div className="admin-empty" role="status"><Loader2 className="spin"/>불러오는 중이에요.</div>:data&&(mode==='operations'?<Operations data={data}/>:mode==='tokens'?<Tokens data={data} offset={offset} setOffset={setOffset}/>:<Prompts data={data} offset={offset} setOffset={setOffset} reload={()=>setVersion(v=>v+1)}/>)}
  </main>;
}
