import React from 'react';
import {ArrowRight,ArrowUpRight,CodeXml,Play,MessageSquare,Sparkles,Users,MessageCircle,SlidersHorizontal,FolderHeart,Presentation,Download,Check,FileText} from 'lucide-react';
import {introResources} from './introContent';
import './introduction.css';

export default function Introduction(){
 return <div className="intro-page"><header className="intro-header"><a href="#" className="intro-brand" aria-label="WiaCoding 소개 처음으로"><CodeXml size={26}/><span>WiaCoding</span></a></header>
 <main className="intro-main"><section className="intro-hero" aria-labelledby="intro-heading"><div className="intro-hero-copy"><div className="intro-eyebrow"><span/>HYUNDAI WIA · VIBE CODING GUIDE</div><h1 id="intro-heading">업무의 아이디어를<br/>첫 개발 프롬프트로,<br/><em>WiaCoding.</em></h1><p>만들고 싶은 것이 있다면, 대화부터 시작하세요.<br/>AI와 함께 해결할 과제를 정리하고<br/>나에게 맞는 첫 개발 프롬프트를 완성합니다.</p><div className="intro-hero-actions"><a href="#app" className="intro-primary">나의 개발 프롬프트 만들기<ArrowRight size={18}/></a><a href="#intro-how" className="intro-text-link">어떻게 이용하나요?<ArrowDownIcon/></a></div></div>
 <div className="intro-video-column"><div className="intro-video-topline"><span>SERVICE FILM</span></div>{introResources.videoUrl?<video className="intro-video" controls preload="metadata" aria-label="WiaCoding 서비스 소개 영상"><source src={introResources.videoUrl} type="video/mp4"/>이 브라우저는 영상 재생을 지원하지 않습니다.</video>:<div className="intro-video-placeholder" aria-label="WiaCoding 소개 영상 준비 중"><div className="intro-orbit orbit-one"/><div className="intro-orbit orbit-two"/><span className="intro-video-corner">WiaCoding / INSIDE</span><div className="intro-film-art"><div className="intro-film-source source-a"><MessageSquare size={17}/><span>YOUR IDEA</span></div><div className="intro-film-letter"><div><CodeXml size={16}/><strong>WiaCoding</strong><span>CODING PROMPT</span></div><span className="intro-letter-kicker">작은 아이디어가, 업무의 변화로.</span><b>나의 아이디어,<br/>개발의 시작으로.</b><div className="intro-letter-rule"/><div className="intro-letter-lines"><i/><i/><i/></div><div className="intro-letter-bottom"><span><Sparkles size={12}/>CRAFTED WITH AI</span><Check size={13}/></div></div><div className="intro-film-source source-b"><Users size={17}/><span>READY TO BUILD</span></div></div><div className="intro-video-caption"><span className="intro-play-mark"><Play size={19} fill="currentColor"/></span><div><strong>영상으로 만나는 WiaCoding</strong><small>소개 영상 준비 중</small></div></div></div>}<p className="intro-video-foot">막연한 아이디어를 정리하고, 만드는 일에 한 걸음 가까이.</p></div></section>
 <section className="intro-benefits" aria-label="WiaCoding의 주요 기능">{[[MessageSquare,'대화로 구체화하는 과제','업무 배경부터 필요한 기능까지 정리'],[Sparkles,'나에게 맞는 개발 프롬프트','과제에 맞춘 질문으로 요구사항 구체화'],[FolderHeart,'동료와 함께 쌓는 아이디어','완성한 프롬프트를 보관하고 공유']].map(([Icon,title,description])=><div key={title}><span><Icon size={21}/></span><div><h2>{title}</h2><p>{description}</p></div></div>)}</section>
 <section className="intro-how" id="intro-how" aria-labelledby="intro-how-heading"><div className="intro-section-head"><div><span className="intro-eyebrow">HOW IT WORKS</span><h2 id="intro-how-heading">아이디어에서 첫 개발 프롬프트까지.</h2></div><p>코딩이 처음이어도 괜찮아요.<br/>업무에서 바꾸고 싶은 일부터 이야기해 보세요.</p></div><div className="intro-steps">{[[MessageCircle,'01','해결할 문제를 이야기하세요','반복되는 업무나 만들고 싶은 서비스를 알려주세요. AI와 대화하며 배경, 사용자, 필요한 기능을 정리해요.','과제 정의'],[SlidersHorizontal,'02','맞춤 질문에 답해 보세요','내 과제에 맞춰 준비된 질문에 답하세요. 놓치기 쉬운 조건까지 살피며 개발에 필요한 요구사항을 구체화해요.','프롬프트 메이킹'],[CodeXml,'03','첫 개발을 시작하세요','완성된 프롬프트를 복사해 바이브코딩 도구에 넣어보세요. 내 프롬프트를 보관하고 동료들의 아이디어도 참고할 수 있어요.','개발 프롬프트']].map(([Icon,n,title,description,tag])=><article key={n}><div className="intro-step-top"><Icon size={23}/><span>{n}</span></div><span className="intro-step-tag">{tag}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
 <section className="intro-guide" id="intro-guide" aria-labelledby="intro-guide-heading"><div className="intro-guide-icon"><Presentation size={35}/><span>PPT</span></div><div className="intro-guide-copy"><span className="intro-eyebrow">QUICK START GUIDE</span><h2 id="intro-guide-heading">처음이라면, 가이드와 함께.</h2><p>과제 정의부터 개발 프롬프트 활용까지.<br/>{introResources.guideUrl?'단계별 사용 방법을 담은 가이드를 내려받아 확인하세요.':'단계별 사용 방법을 담은 가이드를 준비하고 있습니다.'}</p></div>{introResources.guideUrl?<a className="intro-guide-download" href={introResources.guideUrl} download={introResources.guideFilename}><Download size={18}/>PPT 가이드 다운로드<ArrowUpRight size={16}/></a>:<div className="intro-guide-ready"><button disabled><FileText size={18}/>PPT 가이드 준비 중</button><span>등록 후 이곳에서 다운로드할 수 있습니다.</span></div>}</section>
</main>
 <footer className="intro-footer"><span><b>HYUNDAI WIA</b><i/>WiaCoding</span><p>From your everyday idea to your first coding prompt.</p></footer></div>;
}
function ArrowDownIcon(){return <ArrowRight size={15} style={{transform:'rotate(90deg)'}}/>;}
